

<form data-validation = true class="generic-form" action="<?= $requestUrl ?>/user/login" method="POST">
<aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a
        <em id="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p><?= $errorMessage ?></p>
    </aside>
<ul>
            <li>
            <label for="name">Email:</label>
            <input data-required = true data-name = 'email' id="telephone" name="email" type="text" >
             </li>
            <li>
            <label for="name">Mot de passe:</label>
            <input data-required = true data-name = 'motDePasse'  data-length='9' id="telephone" name="password" type="password" >
            </li>
            <input class=" button button-primary " type="submit" value="Se Connecter" > <a class=" button button-cancel" href="<?= $requestUrl ?>">Annuler</a>
</ul>            
</form>