
<h2> <i class="fa fa-user"></i> Création d'un Compte Client </h2>
            

<!-- Formulaire d'ajout de tâche -->
            <form data-required=true class="generic-form" action="<?=$requestUrl?>/user" method="POST">

            <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a
        <em id="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p><?= $errorMessage ?></p>
    </aside>   
            <fieldset>
                    <legend > <i class="fa fa-book"></i> Informations sur la tâche</legend>
                    <ul>
                        <li>
                            <label for="name">Nom:</label>
                            <input id="nom" name="lastName" type="text" value="<?=$lastName?>" />
                        </li>
                        <li>
                            <label for="name">Prenom:</label>
                            <input id="nom" name="firstName" type="text" value="<?=$firstName?>" />
                        </li>
                       
                        <li>
                            <label for="day" >Date de Naissance:</label>
                            <select id="day" name="birthDay">
                                <?php for($day = 1; $day <= 31; $day++): ?>
                                    <option value="<?= $day ?>"><?= $day ?></option>
                                <?php endfor ?>
                            </select>
                            <span>/</span>
                            <select name="birthMonth" >
                                <option value="1">Janvier</option>
                                <option value="2">Février</option>
                                <option value="3">Mars</option>
                                <option value="4">Avril</option>
                                <option value="5">Mai</option>
                                <option value="6">Juin</option>
                                <option value="7">Juillet</option>
                                <option value="8">Août</option>
                                <option value="9">Septembre</option>
                                <option value="10">Octobre</option>
                                <option value="11">Novembre</option>
                                <option value="12">Décembre</option>
                            </select>
                            <span>/</span>
                            <select name="birdhYear" >
                                <?php for($year = 1940; $year < date('Y') -18; $year++): ?>
                                    <option value="<?= $year ?>"><?= $year ?></option>
                                <?php endfor ?>
                            </select>
                        </li>
                        
                        <li>
                            <label for="name">Ville:</label>
                            <input id="nom" name="city" type="text" value="<?=$city?>" />
                        </li>
                        <li>
                            <label for="name">code Postal:</label>
                            <input id="nom" name="zipCode" type="text" value="<?=$zipCode?>" data-type="positiveInteger" />
                        </li>
                        <li>
                            <label for="name">Pays:</label>
                            <input id="nom" name="country" type="text" value="<?=$country?>" />
                        </li>
                        <li>
                            <label for="name">Téléphone:</label>
                            <input id="telephone" name="phone" type="text" value="<?=$phone?>"  data-type="positiveInteger" />
                        </li>
                        
                        
                    </ul>
                </fieldset>
            
           
            <fieldset>
            <legend> <i class="fa fa-lock"></i> informations d'authentification</legend>
            <ul>
            <li>
            <label for="name">Email:</label>
            <input  id="telephone" name="email" type="text" value="<?=$email?>">
             </li>
            <li>
            <label for="name">Mot de passe:</label>
            <input id="telephone" name="password" type="password" >
            </li>
           
            </fieldset>
            
            
            <input  class=" button button-primary " type="submit" value="Cree le Compte" > <a class=" button button-cancel" href="<?= $requestUrl ?>">Annuler</a>
            
            
            </ul>              
          </form>