




<h2>Ajout d'un Produit Alimentaire au Catalogue</h2>
<form class="generic-form" action="<?=$requestUrl?>/admin/meal" method="POST" enctype="multipart/form-data" data-validation >
  <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a
        <em id="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>

    <fieldset>
    <legend> Caracteristique</legend>
    <ul>
    <li>
    <label for="name">Nom:</label>
    <input id="nom" name="Name" type="text" data-required />
    </li>
    <li>
     <label for="description">description:</label>
     <textarea id="adressDescription" name="Description" rows="4"  data-required></textarea>
    </li>
    <li>
    <label for="photo">Photo:</label>
   
    <input type="file" name="Photo"  data-required />
    </li>
    </ul>
    <p>Merci de rennomer le fichier avant de l'envoyer :</p>
    </fieldset>

    <fieldset>
    <legend>Approvision : </legend>
    <ul>
    <li>
    <label for="Stock initial">Stock initial :</label>
    <input class="quantity" name="QuantityInStock" type="text"  data-required data-type="positiveInteger" />
    </li>
    <li>
    <label for="Prix d'achat">Prix d'achat:</label>
    <input class="money" name="BuyPrice" type="text" data-required data-type="positiveNumber" /><em >€</em>
    </li>
    <li>
    <label for="Prix de vente">Prix de vente:</label>
    <input class="money" name="SalePrice" type="text"  data-required data-type="positiveNumber" /><em >€</em>
    </li>
    </ul>
    </fieldset>
    <fieldset>
    <legend>Liste des Articles : </legend>
    <table class="generic-table">
    <thead>
    <tr>
    <th>repas</th>
    <th>prix</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($meals as $meal): ?>
     <tr>
      <td><?= $meal['Name'] ?></td>
      <td><?= $meal['SalePrice'] ?></td>
      </tr>

    <?php endforeach ;?>
    </tbody>          
    </table>
    </fieldset>
    <input class=" button button-primary" type="submit" value="Ajouter" />
        <button class=" button button-cancel" ><a href="<?=$requestUrl?>">Annuler</a></button>
</form>
<script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>