<!-- Message de notification -->


<?php if($flashBag->hasMessages()):?>
    <aside id="notice" class="notice">
        <p><?=$flashBag->fetchMessage()?></p>
    </aside>
<?php endif;?>
<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>

    
            
    <tbody>
    <?php foreach($meals as $meal): ?>

                    <tr>
                    <td><img src="<?=$wwwUrl?>/images/meals/<?=$meal['Photo']?>" alt=""> </td>
                        <td><strong><?= $meal['Name'] ?> </strong><br>  <br> <small><?= $meal['Description'] ?></small> </td>

                    <td><strong><?= $meal['SalePrice'] ?></strong> $</td>
                    </tr>

    <?php endforeach ;?>
   
    </tbody>
</table>
