<!-- Message de notification -->

    <?php if($flashBag->hasMessages()): ?>
    <aside class="notice" id="notice">
        <?=  $flashBag->fetchMessage(); ?>
    </aside>
    <?php endif; ?>

    <?php

        $userSession->getEmail();
     
        
    ?>
<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php foreach($meals as $key => $value): ?>
        <tr>
            <td> <img alt="imageX" src="<?= $wwwUrl. '/images/meals/' .$value['Photo'] ?>"/></td>        
            <td> <strong> <?= $value["Name"]  ?> </strong> </td>
            <td> <?= $value["Description"] ?>  </td>
            <td> <strong> <?= $value["SalePrice"] ."$"?> </strong></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<!--   Photo, Name, Description, SalePrice -->