<!-- Message de notification -->
<aside class="notice">
    <?php if($flashBag->hasMessages()): ?>
        <?=  $flashBag->fetchMessage(); ?>
    <?php endif; ?>

</aside>
<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php foreach($meals as $key => $value): ?>
        <tr>
            <td> <img alt="imageX" src="<?= $wwwUrl. '/images/meals/' .$value['Photo'] ?>"/></td>        
            <td> <strong> <?= $value["Name"]  ?> </strong> </td>
            <td> <?= $value["Description"] ?>  </td>
            <td> <strong> <?= $value["SalePrice"] ."$"?> </strong></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<!--   Photo, Name, Description, SalePrice -->