<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>


</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
<?php if( $userSession->isAuthenticated() == false ){?>

    <ul class="link-list">
        <li><button class="button button-primary "> <a  href="<?=$requestUrl?>/user">Créer Compte</a></button></li>
        <li ><button class="layout-right button button-primary" ><a href="<?=$requestUrl?>/user/login">Connecter</a></button></li>
    </ul>

<?php }else{?>
    <ul class="link-list">
<?php if ($userSession->getAdmin() == 1) { ?>
    
        <li><button class="button button-primary "> <a  href="<?=$requestUrl?>/admin">Admin</a></button></li>
        <li ><button class=" button button-primary" ><a href="<?=$requestUrl?>/admin/meal">Meal</a></button></li>
        
   
<?php }?>
   
        
        

    

<li ><button class=" button button-primary" ><a href="<?=$requestUrl?>/booking">Reserver</a></button></li>

        <li ><button class=" button button-primary" ><a href="<?=$requestUrl?>/order">Commander</a></button></li>
        <em class="no-left-label"><?= 'bonjour '.$userSession->getFirstName();?></em>
        
        <li ><button class="layout-right button button-primary" ><a href="<?=$requestUrl?>/user/logout">Deconnecter</a></button></li>
    </ul>
<?php } ?>
 
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/classes/mainOOP.js"></script>

</body>
</html>