
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.classes.js"></script>
<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<form data-order-step="run" id="order-form" class="generic-form" data-validation >

    <!-- Champ caché stockant le prix de vente du produit alimentaire sélectionné -->
    <input type="hidden" name="salePrice">

    <fieldset id="taille-image">
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label for="meal">Nom :</label>
                <select id="meal" name="meal">
                    <?php foreach($meals as $meal): ?>
                        
                        <option value="<?= $meal['Id'] ?>"> <?= $meal["Name"] ?> </option>
                       
                        <?php endforeach; ?>
                </select>
                <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="Photo du produit">
                    <p></p>
                    <span>Prix : <strong></strong></span>
                </article>
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-type="positiveInteger"><strong id='alert'></strong>
            </li>
            <li>
                <button class="button button-primary no-left-label" type="submit">Ajouter</button>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary"></section>
    </fieldset>
</form>

<ul class="link-list">
    <li>
        <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
        <a class="button button-cancel" href="<?= $requestUrl ?>">Annuler</a>
    </li> 
</ul>
