<h2> <i class="fa fa-cogs"></i> Panneau de configuration</h2>
<form data-required class="generic-form" action="<?=$requestUrl?>/admin" method="GET">


<fieldset>
<legend>Historique des Commandes</legend>
        <table class= "generic-table ">
             <thead >
                <tr>
                    <th>numero commande</th>
                    <th>numero User</th>
                    <th>date creation</th>
                    <th>date succés</th>
                    <th>TVA</th>
                    <th>Montant TVA </th>
                    <th>Total</th>
                    
                   
                </tr>
            </thead>
            <tbody>
                <?php foreach($orders as $order): ?>
                
                    <tr>
                        
                        <td><?= $order['Id'] ?></td>
                        <td><?= $order['User_Id'] ?></td>
                        <td><?= $order['CreationTimestamp'] ?></td>
                        <td><?= $order['CompleteTimestamp'] ?></td>
                        <td><?= $order['TaxRate'] ?></td>
                        <td><?= $order['TaxAmount'] ?></td>
                        <td><?= $order['TotalAmount'] ?></td>
                       
                    </tr>

                <?php endforeach ;?>
            </tbody>
        </table>
</fieldset>



</form>